-- CLASSIFICATION NOTICE: This file is UNCLASSIFIED

-- Magic! vertices have odd ids, edges have even. The 'element_id' in the property
--  table is a pseudo-foreign key, with points into either the vertex or edge tables.

create table vertex (
    id          integer generated by default as identity (start with 1, increment by 2) primary  key
);

create table edge (
    id             integer generated by default as identity (start with 2, increment by 2) primary  key,
    out_vertex_id  integer not null,
    in_vertex_id   integer not null,
    label          varchar(255),
    foreign key (in_vertex_id) references vertex(id),
    foreign key (out_vertex_id) references vertex(id)
);

--  create index in_vertex_id_idx  on edge (in_vertex_id);
--  create index out_vertex_id_idx on edge (out_vertex_id);

create table property (
    element_id    integer,
    key           varchar(255),
    value         varchar(255)
);

create index property_element_id_idx  on property (element_id);
create index property_key_idx         on property (key);
