-- CLASSIFICATION NOTICE: This file is UNCLASSIFIED

-- Magic! vertices have odd ids, edges have even. The 'element_id' in the property
--  table is a pseudo-foreign key, which points into either the vertex or edge tables.

create table vertex (
    id          integer generated by default as identity (start with 1, increment by 2) primary  key
);

create table edge (
    id             integer generated by default as identity (start with 2, increment by 2) primary  key,
    out_vertex_id  integer not null,
    in_vertex_id   integer not null,
    label          varchar(255),
    foreign key (in_vertex_id) references vertex(id),
    foreign key (out_vertex_id) references vertex(id)
);

create index edge_in_vertex_id_idx  on edge (in_vertex_id);
create index edge_out_vertex_id_idx on edge (out_vertex_id);

-- types are 'V' or 'E' for vertex or edge, respectively
create table property (
    element_id    integer,
    type          character(1) check (type in ('V', 'E')),
    key           varchar(255),
    value         varchar(255)
);

create index property_id_idx     on property (element_id, type);
create index property_key_idx    on property (key);